"""
" gvimrc 2015
" Author: Martin Lafreniere
"
" Free to use, modify or distribute. No warranties.
"""
scriptencoding utf-8

if !exists('g:gvimrcloaded')
  set lines=48 columns=100
  let g:gvimrcloaded = 1
endif

" Gui options
set guioptions=egrLtac
if has('win32') || has('win64')
  set guifont=Consolas:h11:cANSI
else
  set guifont=Bitstream\ Vera\ Sans\ Mono\ 10
endif

set renderoptions=type:directx

" Mouse options
set mousehide

