"""
" vimrc 2015
" Author: Martin Lafreniere
"
" Free to use, modify or distribute. No warranties.
"""
scriptencoding utf-8

set nocompatible
set cpoptions+=$

" Define which vim directory is in use
if has('win32') || has('win64')
  let g:vim_home = expand("~/vimfiles")
else
  let g:vim_home = expand("~/.vim")
end

" execute pathogen#infect()

" Buffer/File encoding and formatting
set encoding=utf-8
set fileencoding=utf-8
set fileformats=unix,dos,mac
set fileformat=unix

" syntax enable
" filetype plugin indent on

" Plugin
call plug#begin(g:vim_home . "/plugged")

Plug 'altercation/vim-colors-solarized'
Plug 'vim-airline/vim-airline'
Plug 'jlanzarotta/bufexplorer'
Plug 'scrooloose/nerdtree'
Plug 'luochen1990/rainbow'
Plug 'godlygeek/tabular'

call plug#end()

" Vim colors
set background=dark
if has('gui_running')
  colorscheme solarized
else
  colorscheme peachpuff
endif

" Set viminfo folder
let &viminfo = &viminfo.",n".g:vim_home.'/viminfo'

" Status line, line numbering and command line.
set number
set cmdheight=2
set showcmd
set wildmenu
set laststatus=2

" Set default whitespacings rules
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set list
set listchars=tab:>-,trail:$

" Set default search options
set incsearch
set hlsearch
set ignorecase
set smartcase

" Buffer options
set hidden
set backspace=1

" Text line options
"set textwidth=160
set nowrap
set formatoptions+=cqrn
set formatoptions-=o

" Working Directory
if has('win32') || has('win64')
  set directory=~/_backup
else
  set directory=~/.backup
endif
set autochdir

" Error handling
set visualbell t_vb=

" Terminal mouse
set mouse=a

" Map leader
nnoremap <space> <nop>
let mapleader = " "

" Configure NETRW
if has('win32') || has('win64')
  let g:netrw_scp_cmd = "pscp -scp"
  let g:netrw_sftp_cmd = "psftp"
endif

" Configure AIRLINE
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_left_sep = '►'
let g:airline_right_sep = '◄'


" Configure RAINBOW PARENS
let g:rainbow_active = 1
let g:rainbow_conf = {}
let g:rainbow_conf['guifgs']      = ['#b58900', '#268bd2', '#cb4b16', '#d33682']
let g:rainbow_conf['ctermfgs']    = ['3', '4', '9', '5']
let g:rainbow_conf['operators']   = '_,_'
let g:rainbow_conf['parentheses'] = ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold']
let g:rainbow_conf['separately']  = { '*': {} }

" Vim settings based on workstation
if filereadable(g:vim_home."/vimrc.local")
  runtime vimrc.local
endif

