"""
" File: vimrc
" Author: Martin Lafreniere
" Data: 2018-12-26
"
" Free to use, modify or distribute. No warranties.
"""
scriptencoding utf-8

set nocompatible
set cpoptions+=$

" Define which vim directory is in use
if has('win32') || has('win64')
  let g:vim_home = expand("~/vimfiles")
else
  let g:vim_home = expand("~/.vim")
end

" Buffer/File encoding and formatting
set encoding=utf-8
set fileencoding=utf-8
set fileformats=unix,dos,mac
set fileformat=unix

" syntax enable
filetype plugin indent on

" Vim colors
set background=dark
colorscheme peachpuff

" Set viminfo folder
let &viminfo = &viminfo.",n".g:vim_home.'/viminfo'

" Status line, line numbering and command line.
set number
set cmdheight=2
set showcmd
set wildmenu
set laststatus=2

" Set default whitespacings rules
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set list
set listchars=tab:>-,trail:$

" Set default search options
set incsearch
set hlsearch
set ignorecase
set smartcase

" Buffer options
set hidden
set backspace=1

" Text line options
"set textwidth=160
set nowrap
set formatoptions+=cqrn
set formatoptions-=o

" Working Directory
if has('win32') || has('win64')
  set directory=~/_backup
else
  set directory=~/.backup
endif
set autochdir

" Error handling
set visualbell t_vb=

" Terminal mouse
set mouse=a

" Map leader
nnoremap <space> <nop>
let mapleader = " "
